### ISSUE TITLE
Archive issue with swift 4.2 version

### ISSUE THREAD

**Issue by taglia3** [lokalise/live-edit-ios#3]
I receive this error during the archive:
ld: bitcode bundle could not be generated because 

> '.../Pods/LokaliseLiveEdit/LokaliseLiveEdit.framework/LokaliseLiveEdit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '.../Pods/LokaliseLiveEdit/LokaliseLiveEdit.framework/LokaliseLiveEdit' for architecture arm64

Prior to the last update all works fine. Could you verify please?

**Comment by AnujD7781** [comment]
I am also getting same error during archive,
Can someone please verify and reply on this thread with the solution?

**Comment by Fedya-L** [comment]
Please use version 0.3.1.
If you are already using it and still getting this error, contact us trough our support chat.
